services:
    kadi:
        build: ./
        depends_on:
            - postgres
            - redis
            - elasticsearch
        ports:
            - 80:80
            - 443:443
        volumes:
            - kadi:/opt/kadi/
    postgres:
        image: postgres:17
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=kadi
            - POSTGRES_USER=kadi
            - POSTGRES_PASSWORD=kadi
        volumes:
            - postgres:/var/lib/postgresql/data
    redis:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - redis:/data
    elasticsearch:
        image: elasticsearch:8.17.0
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.security.http.ssl.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

volumes:
    postgres:
    redis:
    elasticsearch:
    kadi: