apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kadi-storage
  name: kadi-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
