apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-elasticsearch"
  name: "{{ .Release.Name }}-elasticsearch"
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-elasticsearch"
