apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  kadi.py: |
    AUTH_PROVIDERS = [{"type": "local"}]
    SERVER_NAME = {{ .Values.hostname | quote }}
    SECRET_KEY = "kadi"
    SQLALCHEMY_DATABASE_URI = "postgresql://kadi:kadi@{{ .Release.Name }}-postgres-rw/kadi"
    STORAGE_PATH = "/opt/kadi/storage"
    MISC_UPLOADS_PATH = "/opt/kadi/uploads"
    SMTP_HOST = "localhost"
    SMTP_PORT = 25
    SMTP_USERNAME = ""
    SMTP_PASSWORD = ""
    ELASTICSEARCH_HOSTS = "http://{{ .Release.Name }}-elasticsearch:9200"
    RATELIMIT_STORAGE_URI = "redis://{{ .Release.Name }}-redis:6379/0"
    CELERY_BROKER_URL = "redis://{{ .Release.Name }}-redis:6379/0"