apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 100
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: {{ .Values.image }}
          name: {{ .Release.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/kadi/storage
              name: kadi-storage
            - mountPath: /opt/kadi/uploads
              name: kadi-uploads
            - mountPath: /opt/kadi/config
              name: kadi-config
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
      restartPolicy: Always
      volumes:
        - name: kadi-storage
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-storage
        - name: kadi-uploads
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-uploads
        - name: kadi-config
          configMap:
            name: kadi-configmap