apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
