apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-redis"
  name: "{{ .Release.Name }}-redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-redis"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-redis"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: redis:7
          name: "{{ .Release.Name }}-redis"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis
      restartPolicy: Always
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-redis"
