apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-redis"
  name: "{{ .Release.Name }}-redis"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.internalRedisSettings.storage.size }}
