apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-redis"
  name: "{{ .Release.Name }}-redis"
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-redis"
