AUTH_PROVIDERS = [{"type": "local"}]
SERVER_NAME = "localhost"
SECRET_KEY = "kadi"
SQLALCHEMY_DATABASE_URI = "postgresql://kadi:kadi@postgres/kadi"
STORAGE_PATH = "/opt/kadi/storage"
MISC_UPLOADS_PATH = "/opt/kadi/uploads"
SMTP_HOST = "localhost"
SMTP_PORT = 25
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
ELASTICSEARCH_HOSTS = "http://elasticsearch:9200"
RATELIMIT_STORAGE_URI = "redis://redis:6379/0"
CELERY_BROKER_URL = "redis://redis:6379/0"